### PR TITLE
Added hsv colors to colored edges. Added comments.

### PR DESCRIPTION
**Pull request by sf87adin**
I am not sure if this is ok for day mode (see the comment in `style.ts`).

### CODE REVIEW

**Comment by KonradHoeffner** [comment]
Good point, I totally forgot about day mode. Thanks for the PR! I will run it through prettier (which is what the lint-staged commit hook normally does that only seems to work on Linux right now), test it and merge it.

**Comment by KonradHoeffner** [comment]
By the way, you should also be able to run the code formatter manually with `npx prettier js -w`, but I will do this now.

**Comment by KonradHoeffner** [comment]
Just noticed, I wrote "HSV" but I used "HSL" instead because I mixed up the two color models.
HSL is [well supported](https://caniuse.com/css3-colors) in CSS directly but HSV doesn't seem to be supported at all right now.
HSL could actually match the use case better because it allows setting an equal brightness for all edges.

**Comment by KonradHoeffner** [comment]
Looks good in day mode too.

**Comment by sf87adin** [comment]
> By the way, you should also be able to run the code formatter manually with `npx prettier js -w`, but I will do this now.

Oh thats good, I've just seen, here have been many deviations from the style code I am sorry for that.
I'm curiose does this applay a standardized code style like husky or is this defined in some place in the project?

A little note for the command, for me it's probalby better to add `--cache` to not modify all files for the commit.
`npx prettier js -w --cache`

> Just noticed, I wrote "HSV" but I used "HSL" instead because I mixed up the two color models. HSL is [well supported](https://caniuse.com/css3-colors) in CSS directly but HSV doesn't seem to be supported at all right now. HSL could actually match the use case better because it allows setting an equal brightness for all edges.

That's great, i really didn't knew `hsl()` is possible in CSS.

**Comment by KonradHoeffner** [comment]
> Oh thats good, I've just seen, here have been many deviations from the style code I am sorry for that. I'm curiose does this applay a standardized code style like husky or is this defined in some place in the project?
> 
> A little note for the command, for me it's probalby better to add `--cache` to not modify all files for the commit. `npx prettier js -w --cache`

The code style files are listed in <https://github.com/snikproject/graph#code-style>.
I have expanded that section to explain it in more detail.
Thanks for the heads up with the new cache option!

**Pull request merged**
