### PR TITLE
Self host jQuery

### PR DESCRIPTION
**Pull request by sf87adin**
Put jQuery into /js directory and deliver it by our own. Also had to change CRLF to LF on index.html since the HTML parser (latest version?)  doesn't accept CRLF.  #150

### CODE REVIEW

**Comment by sf87adin** [comment]
~~I suggest the change of the `index.html` should fix the problem concerning the EOL problems.~~
Sorry that there are aigain two problems solved using one pull request. But as changed the `index.html` for the jQuery thing (`line 14`) I had these changes left over.

I figured out my problem concerning the EOL, it was duo to git converting the LF to CRLF because I'm on Windows.
This also lead to a problem with the here included jQuery script. The hash defined in the `index.html` didn't matched the file since the characters where switched and so the file was blocked to loaded.
I just disabled these strange switching of EOL characters using the following command:
`git config --global core.autocrlf false`
For me it doesn't matter, since I'am using Visual Studio Code as IDE which knows how to interprete LF even on Windows.

**Comment by KonradHoeffner** [comment]
I think the EOF error is actually a bug in the new HTML parser of Vite, I created a bug report at <https://github.com/vitejs/vite/issues/10580#issuecomment-1288670945>.
This error is triggered by the following HTML snippet, which I believe is legal HTML and which is created by the [https://prettier.io/docs/en/options.html#html-whitespace-sensitivity](HTML Whitespace Sensitivity option that Prettier defaults to  since version 1.15).

```
 <noscript
            ><h1>JavaScript is off. <a href="http://enable-javascript.com/">Please enable</a> to view site.</h1></noscript
        >
```

**Comment by KonradHoeffner** [comment]
While I agree that self hosting jQuery is a good idea, I don't want to put it under version control, because that would put it outside our dependency management workflow (a problem the current solution has as well) and also create huge diffs.
Ideally, it would be added as a dependency to package.json and included in the golden layout related SNIK Graph files, however the golden layout library expects it to be available as the global variable `$`, which this does not achieve.

So we have the following options:

1. (current) include jQuery over from a CDN. Advantages: simple, no work required. Disadvantages: Additional network connection (potential latency increase), outside dependency management workflow, potential legal problems, CDN could theoretically break or link could change, though in practice they seem pretty reliable and SNIK Graph isn't a life critical application like a peacemaker that needs to have 100% uptime. If it can be improved with no downside then why not though.
2. (this pull request) add jQuery to the source folder `js` of  this repository. Advantages: No legal problems, reliable, fast. Downside: Outside dependency management workflow, external libraries are not meant to be checked in to version control and produce large diffs.
3. Add it like a normal npm dependency to package.json and import it to `$` in `view.ts` and `viewLayout.ts`.  Advantage: This would be a great solution because it adheres to our normal workflow. Disadvantage: **It does not work**, because the GoldenLayout library expects it to be available as a global variable. Takes more disk space (1.7MB on the server.
4. Add it like a normal npm dependency to package.json but include it in index.html as a global variable. Advantage: Second most elegant solution after 3 but only works in local dev mode preview because vite will bundle all dependencies into the dist folder and dependencies in their original form are not included in the bundle.

At the moment I will keep the current state and not merge this pull request but may reconsider in the future to one of the 3 other options, preferably 3. and 4. if they are workable somehow.

**Comment by KonradHoeffner** [comment]
Actually there is a way to achieve something between 3. and 4. explained in <https://github.com/vitejs/vite/discussions/3744>.
In index.html:

    <head>
    ....
    <script type="module">
         import $ from "jquery";
         window.jQuery = window.$ = $;
     </script>
     <script type="module" src="./js/browser/main.ts"></script>
    </head>
    ....

**Comment by KonradHoeffner** [comment]
In some cases (tested without cache) this gives an insane speed boost. However I compared the local built version to the one on the server so those numbers can't be taken as absolutes but still one more motivation to switch it out.

## with CDN
Screenshot from 2022-10-24 13-42-03

## without CDN
Screenshot from 2022-10-24 13-42-13

**Comment by KonradHoeffner** [comment]
Replaced with 96a577c7940313669e209159238200de94ce6693.

**Pull request closed without merging**
