### PR TITLE
Layout (compound) fit view + option for colored edges

### PR DESCRIPTION
**Pull request by sf87adin**
Changed cose to grid mode to display as much nodes as possible.

Added option for colored edges.

### CODE REVIEW

**Comment by KonradHoeffner** [comment]
Original colors (gray for non-interlinks, dark yellow for interlinks):
Screenshot from 2022-10-21 14-50-52

Colored edges:
Screenshot from 2022-10-21 14-51-15

**Comment by KonradHoeffner** [comment]
I tried to increase the brightness of the edges but the problem was the opacity of them because the original color was not gray but white with low opacity, so any other color would be less bright.

**Comment by KonradHoeffner** [comment]
I am not sure if the RGB color model is best with this algorithm, because the luminositiy may be different. Trying the HSL color model.

**Comment by KonradHoeffner** [comment]
Thanks for the PR, merged! (only the color part for now, though)

**Comment by KonradHoeffner** [comment]
P.S.: I did it manually, I think GitHub will see it as closed instead but at least your author information should be preserved. Hope that is OK.

**Comment by sf87adin** [comment]
Concerning the layout i was not aware the function does some more than displaying all visible nodes very small so nothing can be seen.
grafik
I will have another look on that and try to find a solution.

**Comment by sf87adin** [comment]
For the colors I added another pull request, hope the hierarchy is consistent.
Pull request [https://github.com/snikproject/graph/pull/392](https://github.com/snikproject/graph/pull/392 )

**Pull request closed without merging**
